### ISSUE TITLE
Proposal: Favor EnumerateFile/EnumerateDirectories over GetFiles/GetDirectories

### ISSUE THREAD

**Issue by Keboo** [IntelliTect/CodingStandards#16]
We should flag usages of GetFiles/GetDirectories and **_suggest_** using EnumerateFiles/EnumerateDirectories

**Comment by Keboo** [comment]
Worth noting, that when fully iterating in net6 there is little difference between the methods. However, I believe the guidance is still good as the Get* methods can be problematic and favoring the Enumerate* avoids that trap.
![image](https://user-images.githubusercontent.com/952248/150196904-9ecfaf78-c414-4928-8fec-7ced976b00a5.png)

**Comment by adamskt** [comment]
Should we make the analyzer only work on projects with a TFM < net6 ?

**Comment by Keboo** [comment]
No, i think the guidance is still good. It is still good to favor the Enuemerate* methods to avoid walking into the perf trap. Especially since the guidance is to consider, not always (hence the suggest level on the analyzer). Given the perf doesn't really matter when fully enumerating, and one method has a perf trap, I would still suggest that people favor the enumerable methods as there is there is very little reason to not use them.
