### ISSUE TITLE
Target netstandard 2.0 with our analyzer

### ISSUE THREAD

**Issue by adamskt** [IntelliTect/CodingStandards#43]
Can anyone think of a reason not to target netstd 2.0?

**Comment by Keboo** [comment]
I believe the reason for netstandard1.3 is to support oldner MSBuild (ie. older VS versions).

**Comment by adamskt** [comment]
I think that's a valid reason to keep it where it's at.  I have pretty much eliminated anything lower than VS2019 on any of my environments, but I imagine I'm an outlier.  Closing this issue for now.
