### ISSUE TITLE
Change naming standard for fields to be _PascalCase

### ISSUE THREAD

**Issue by Keboo** [IntelliTect/CodingStandards#6]
Current coding standard:
> Prefix fields (if they are indeed needed) with underscore and then use ‘PascalCasing’ and wrap them with a property (even if the end result is private).
Exception: Unless you need to pass a member value by ref, and it cannot be a local variable. Example: Maining an internal reference count using Interlocked.
This largely removes the need for readonly fields in favor of properties.

After creating the analyzer there has been a lot of discussion on if the coding standards should be changed to have the naming for fields be underscore camel case.

**Comment by adamskt** [comment]
Here is a perfect example of a recent Microsoft OSS product that uses underscore + camelCase: https://github.com/dotnet/command-line-api/blob/master/src/System.CommandLine/Builder/CommandLineBuilder.cs#L13

**Comment by Keboo** [comment]
As per discussion. The naming standard will remain as underscore PascalCase for fields. It is important to also note, that we realize that this does not match the default naming standard used by many projects. This is fine. For people using this analyzer on those projects they are expected to disable this one. Mark please provide a write up for this that can be added to the wiki.

@adamskt @MarkMichaelis
