### ISSUE TITLE
Add analyzer for `async void` method signatures.

### ISSUE THREAD

**Issue by KennethWhite** [IntelliTect/CodingStandards#7]
These instances are almost always going to be unintentional. They cause the calling thread to fire and forget which can lead to some subtle and difficult to track down bugs, one of which I just recently dealt with.

Solution: flag them as warnings or even errors and recommend changing to `async Task`

**Comment by Keboo** [comment]
I believe we want this to only be a suggestion since we want to encourage turning on warnings as errors.
